// LYRA PULSE semantic color tokens. Keep brand and UI colors centralized here.
export const colors = {
  primary: '#172554',
  primaryDark: '#0B1638',
  primaryBlue: '#2563EB',
  secondary: '#4F46E5',
  secondaryDark: '#4338CA',
  secondarySoft: '#EEF2FF',
  accent: '#06B6D4',
  background: '#F5F7FB',
  surface: '#FFFFFF',
  surfaceMuted: '#F8FAFC',
  textPrimary: '#0F172A',
  textSecondary: '#64748B',
  border: '#E2E8F0',
  borderStrong: '#94A3B8',
  hover: '#F1F5F9',
  focus: '#2563EB',
  disabled: '#94A3B8',
  success: '#16A34A',
  successDark: '#15803D',
  successBackground: '#F0FDF4',
  warning: '#F59E0B',
  warningDark: '#92400E',
  warningBackground: '#FFFBEB',
  error: '#DC2626',
  errorDark: '#B91C1C',
  errorBackground: '#FEF2F2',
  info: '#2563EB',
  infoDark: '#1D4ED8',
  infoBackground: '#EFF6FF',
  sidebarText: '#CBD5E1',
  sidebarMuted: '#94A3B8',
  sidebarActive: 'rgba(37, 99, 235, 0.24)',
  sidebarHover: 'rgba(203, 213, 225, 0.09)',
  sidebarDivider: 'rgba(203, 213, 225, 0.12)',
  focusRing: 'rgba(37, 99, 235, 0.12)',
  focusSubtle: 'rgba(37, 99, 235, 0.10)',
  selection: 'rgba(37, 99, 235, 0.18)',
  selected: 'rgba(37, 99, 235, 0.08)',
}

export const palette = {
  primary: {
    navy: colors.primary,
    royal: colors.primaryBlue,
    indigo: colors.primaryBlue,
    purple: colors.secondary,
    cyan: colors.accent,
  },
  success: colors.success,
  warning: colors.warning,
  error: colors.error,
  info: colors.info,
  background: colors.background,
  paper: colors.surface,
  surfaceMuted: colors.surfaceMuted,
  text: {
    primary: colors.textPrimary,
    secondary: colors.textSecondary,
    muted: colors.textSecondary,
  },
  border: colors.border,
  surface: colors.surface,
  lyra: {
    sidebarBackground: colors.primaryDark,
    sidebarText: colors.sidebarText,
    sidebarMuted: colors.sidebarMuted,
    sidebarActive: colors.sidebarActive,
    sidebarHover: colors.sidebarHover,
    sidebarDivider: colors.sidebarDivider,
  },
}